/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardConfigurationsRouteImport } from './routes/dashboard.configurations'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'

const LoginLazyRouteImport = createFileRoute('/login')()
const Error503LazyRouteImport = createFileRoute('/error-503')()
const Error500LazyRouteImport = createFileRoute('/error-500')()
const Error404LazyRouteImport = createFileRoute('/error-404')()
const Error403LazyRouteImport = createFileRoute('/error-403')()
const Error401LazyRouteImport = createFileRoute('/error-401')()

const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const Error503LazyRoute = Error503LazyRouteImport.update({
  id: '/error-503',
  path: '/error-503',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error-503.lazy').then((d) => d.Route))
const Error500LazyRoute = Error500LazyRouteImport.update({
  id: '/error-500',
  path: '/error-500',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error-500.lazy').then((d) => d.Route))
const Error404LazyRoute = Error404LazyRouteImport.update({
  id: '/error-404',
  path: '/error-404',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error-404.lazy').then((d) => d.Route))
const Error403LazyRoute = Error403LazyRouteImport.update({
  id: '/error-403',
  path: '/error-403',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error-403.lazy').then((d) => d.Route))
const Error401LazyRoute = Error401LazyRouteImport.update({
  id: '/error-401',
  path: '/error-401',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error-401.lazy').then((d) => d.Route))
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigurationsRoute = DashboardConfigurationsRouteImport.update({
  id: '/configurations',
  path: '/configurations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/error-401': typeof Error401LazyRoute
  '/error-403': typeof Error403LazyRoute
  '/error-404': typeof Error404LazyRoute
  '/error-500': typeof Error500LazyRoute
  '/error-503': typeof Error503LazyRoute
  '/login': typeof LoginLazyRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/configurations': typeof DashboardConfigurationsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error-401': typeof Error401LazyRoute
  '/error-403': typeof Error403LazyRoute
  '/error-404': typeof Error404LazyRoute
  '/error-500': typeof Error500LazyRoute
  '/error-503': typeof Error503LazyRoute
  '/login': typeof LoginLazyRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/configurations': typeof DashboardConfigurationsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/error-401': typeof Error401LazyRoute
  '/error-403': typeof Error403LazyRoute
  '/error-404': typeof Error404LazyRoute
  '/error-500': typeof Error500LazyRoute
  '/error-503': typeof Error503LazyRoute
  '/login': typeof LoginLazyRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/configurations': typeof DashboardConfigurationsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/error-401'
    | '/error-403'
    | '/error-404'
    | '/error-500'
    | '/error-503'
    | '/login'
    | '/dashboard/clients'
    | '/dashboard/configurations'
    | '/dashboard/history'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error-401'
    | '/error-403'
    | '/error-404'
    | '/error-500'
    | '/error-503'
    | '/login'
    | '/dashboard/clients'
    | '/dashboard/configurations'
    | '/dashboard/history'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/error-401'
    | '/error-403'
    | '/error-404'
    | '/error-500'
    | '/error-503'
    | '/login'
    | '/dashboard/clients'
    | '/dashboard/configurations'
    | '/dashboard/history'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  Error401LazyRoute: typeof Error401LazyRoute
  Error403LazyRoute: typeof Error403LazyRoute
  Error404LazyRoute: typeof Error404LazyRoute
  Error500LazyRoute: typeof Error500LazyRoute
  Error503LazyRoute: typeof Error503LazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-503': {
      id: '/error-503'
      path: '/error-503'
      fullPath: '/error-503'
      preLoaderRoute: typeof Error503LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-500': {
      id: '/error-500'
      path: '/error-500'
      fullPath: '/error-500'
      preLoaderRoute: typeof Error500LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-404': {
      id: '/error-404'
      path: '/error-404'
      fullPath: '/error-404'
      preLoaderRoute: typeof Error404LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-403': {
      id: '/error-403'
      path: '/error-403'
      fullPath: '/error-403'
      preLoaderRoute: typeof Error403LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-401': {
      id: '/error-401'
      path: '/error-401'
      fullPath: '/error-401'
      preLoaderRoute: typeof Error401LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configurations': {
      id: '/dashboard/configurations'
      path: '/configurations'
      fullPath: '/dashboard/configurations'
      preLoaderRoute: typeof DashboardConfigurationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardConfigurationsRoute: typeof DashboardConfigurationsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardConfigurationsRoute: DashboardConfigurationsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  Error401LazyRoute: Error401LazyRoute,
  Error403LazyRoute: Error403LazyRoute,
  Error404LazyRoute: Error404LazyRoute,
  Error500LazyRoute: Error500LazyRoute,
  Error503LazyRoute: Error503LazyRoute,
  LoginLazyRoute: LoginLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
